name=ag1171
version=1.0.0
author=Herbert van Til
maintainer=
sentence=The AG1171 library controls an AG1171 SLIC module by managing power, ring mode, and programmable ring cadence generation (frequency and on/off timing) using non-blocking timing logic.
category=Phone bell ringing
url=""
architectures=